mybatis:
  typeAliasesPackage: com.jujingyun.huiyuan.entiry
  mapperLocations: classpath:mapper/*.xml
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 80

#开发配置
spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/

  datasource:
    url: jdbc:mysql://59.110.18.217:3307/huiyuan_online?ullNamePatternMatchesAll=true&amp;serverTimezone=GMT%2b8?useUnicode=true&characterEncoding=utf8
    username: root
    password: Jordon918
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource